modules/codelists/pages/index.adoc
I added a section briefly describing the codelist identifiers. It satisfies the request, but I'm not sure it is enough.
=> TEDEFO-666 : added short section about the codelist identifiers.

modules/schema/pages/acronyms-and-abbreviations.adoc, modules/schema/pages/notices-xml-structure.adoc
Added OPP and OPT terms to Abbreviations section. Described them in a new section "4.2.3. Business Terms" under 4.2. Notices XML structure.
Please review the wording. I'm sure it could be improved!
=> TEDEFO-829 

modules/notice-types/pages/index.adoc
Also remove note on the "legacy" subfolder, as it is now removed.
=> notice-types: Describe new properties in notice-types.json

modules/schema/pages/procedure-lot-part-information.adoc
Fixed bad link.
Updated Award Criteria section to be more clear about BT-543 Award Criteria Complicated
=> TEDEFO-1495: Updated info for BT-543 Award Criteria Complicated

modules/schema/pages/competition-results.adoc, modules/schema/pages/contract-modification-notice.adoc
=> Contract modification documentation update

modules/schema/pages/competition-results.adoc, modules/schema/pages/procedure-lot-part-information.adoc, modules/schema/pages/withheld-publication.adoc
About new and existing Framework amounts
=> Next regulation framework values

modules/schema/pages/competition-results.adoc, modules/schema/pages/procedure-lot-part-information.adoc
Miscellaneous documentation update
=> Miscellaneous corrections

modules/schema/pages/identifiers.adoc
Update of the table in the identifiers section needed
=> BT-22 shall have a schemeName value of "InternalID" (TEDEFO-1583)

modules/schema/pages/parties.adoc, modules/schema/pages/procedure-lot-part-information.adoc
TEDEFO-1562 specified BTs for some elements
TEDEFO-1568 fixed closing tags
TEDEFO-1461 stated BT-44 Prize Rank must be an integer 
TEDEFO-1424 stated that cac:AddressLine should not repeat
=> TEDEFO-1562 specified BTs for stated elements

modules/schema/pages/competition-results.adoc, modules/schema/pages/parties.adoc, modules/schema/pages/terms-and-definitions.adoc
Documentation update proposal based on some definitions review. Pending definitions confirmation. To be applied on v 1.0 onward.
=> Documentation update based on some new definitions (TEDEFO-1754)

modules/schema/pages/competition-results.adoc, modules/schema/pages/documents-forms-and-notices.adoc, modules/schema/pages/identifiers.adoc, modules/schema/pages/introduction.adoc, modules/schema/pages/notice-content.adoc, modules/schema/pages/notice-information.adoc, modules/schema/pages/notices-xml-structure.adoc, modules/schema/pages/procedure-lot-part-information.adoc, modules/schema/pages/references.adoc, modules/schema/pages/withheld-publication.adoc
=> Tedefo 1773 documentation update following the regulation amendment

modules/schema/pages/schemas.adoc
Referenced namespaces needed to be updated starting from version 1.3 upwards
=> eForms extensions namespaces updates (TEDEFO-1901)

modules/schema/pages/identifiers.adoc, modules/schema/pages/procedure-lot-part-information.adoc
To be applied from SDK 1.3 upwards
=> Inaccuracies fix 202303

modules/schema/pages/identifiers.adoc
Adding OPP-090 to Identifiers sections from SDK 1.3 onwards
=> Adding OPP-090 to the Identifiers section (TEDEFO-2230)

modules/schema/pages/change-notice.adoc
To be applied from SDK 1.3.x upwards
=> Update regarding allowed formats for BT-758 (TEDEFO-2246)

modules/fields/pages/index.adoc, modules/schema/pages/procedure-lot-part-information.adoc
To be applied to SDK 1.3 onwards.
=> Procurement Relaunch Indicator (TEDEFO-1926) and Measure (TEDEFO-2050) clarification

modules/fields/pages/index.adoc
Let me know if this is good enough.
Perhaps we could find an example (once the fields are defined) for example an amount and a currency and create a section to cover this topic.
=> TEDEFO-2436 documentation about attributes

modules/schema/pages/change-notice.adoc
To be applied to doc v1.3 upwards
=> Clarification about the presence of the efac:Change node. (TEDEFO-2541)

modules/schema/pages/procedure-lot-part-information.adoc
=> Allow for multiple Subcontract Obligation (TEDEFO-2566)

modules/schema/pages/procedure-lot-part-information.adoc
To be applied from Doc v 1.3 upwards
=> Clarification about the use of Previous Notice (OPP-090)

modules/schema/pages/withheld-publication.adoc
Past tense. To be applied from Doc V 1.3 upwards
=> Typo fixing (TEDEFO-2576)

modules/schema/pages/procedure-lot-part-information.adoc
to be added to Doc version 1.10
=> Details about possible Duration components combination (TEDEFO-2810)

modules/schema/pages/parties.adoc
To apply from v 1.3 to the latest
=> Clarification about Buyer and Contracting Party (TEDEFO-2836)

modules/schema/pages/parties.adoc
To be applied on version 1.11 and previous versions
=> Improve explanation about (#) for Rooles/Subroles (TEDEFO-3026)

modules/schema/pages/parties.adoc
To be applied from 1.4.x to 1.10.x
=> Clarify required use of Roles/Subroles (TEDEFO-3026)

modules/schema/pages/notice-information.adoc
To be applied to versions 1.10.x and 1.11.x
=> Clarification about Notice Dispatch Dates controls (TEDEFO-3072)

modules/eforms/pages/active-versions/index.adoc, modules/eforms/pages/roadmap/index.adoc
I revised the roadmap and active version pages. Please provide me with your comments.
=> Revised active versions and roadmap pages.

modules/schema/pages/procedure-lot-part-information.adoc
In case of FSR application, at least a declaration is needed
=> BT-682 mandatory when BT-681 is set to true (TEDEFO-3309)

modules/schema/pages/change-notice.adoc
=> Updating element order in the sample extract (TEDEFO-3276)

modules/ROOT/pages/active-versions/index.adoc
Add SDK 1.11 and remove SDK 1.5 and earlier.
=> Update active versions table

modules/ROOT/pages/active-versions/index.adoc
As announced in the eForms workshop.
=> active-versions: Update extended lifespan dates for 1.6, 1.7 and 1.8

modules/ROOT/pages/preview/index.adoc
Corrected app version/ date and added info on automated notifications
=> Update Preview: eN2

antora.yml
to match changes introduced with SDK 1.12
=> Updating documentation on Selection Criteria

modules/ROOT/pages/preview/index.adoc
ALso create a title for know issues, as for other apps.
=> preview: Add concurrency known issue for CVS

modules/guide/pages/validation.adoc
I am not sure if branching from 1.14.x and merging to 1.14.x is the way to go, I guess it is.
Also see https://citnet.tech.ec.europa.eu/CITnet/jira/browse/TEDEFO-3978
=> TEDEFO-3978 fix of typo (performed -> perform)

modules/ROOT/pages/active-versions/index.adoc, modules/ROOT/pages/preview/index.adoc
Also remove know issue for CVS, as it has been solved.
=> Update active versions
